/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lib */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "lib.pb-c.h"
